#!/usr/bin/env bash
# BinaryWormholeMerger -- Phase 1 initial-data validation (research/merger/Reference.md).
#
# Phase 1 is the GO/NO-GO gate: every statement in it is about the data AT
# t = 0, so every run here sets `max_steps = 0`.  The evolution never starts;
# BinaryWormholeLevel::specific_post_init writes the t = 0 row of
# constraint_norms.dat and the step-0 plotfile, and that is the measurement.
#
# Checks.  A/B/C are the three gates Reference.md names; D and E exist because the
# first pass at B and C measured the grid rather than the physics.
#   A  single-throat limit -- b_B = 0, no bare mass, no momenta, reproduces
#      Examples/SupportedWormholeCollapse on the same grid (fcompare on chi;
#      phi up to the subtracted asymptotic constant)
#   B  momentum constraint at t = 0 -- exactly zero with momenta off (A_ij is
#      identically zero, so this is a bit-level check), and truncation-error
#      small AND CONVERGENT with Bowen-York momenta on
#   C  Hamiltonian defect scaling -- L2_Ham(t=0) falls like 1/d^2 as the
#      separation doubles at fixed resolution, measured against the
#      single-throat run at the same grid, which is the discretisation floor
#   D  resolution ladder -- the control B and C both turned out to need.  B's
#      first pass carried a bare mass (a puncture: chi -> 0, so the whole-domain
#      L2 of a formally singular constraint has no continuum limit) on a throat
#      only 1-2 cells across, and duly came out non-monotonic.  D reruns the
#      same physics with no puncture and the throat resolved.
#   E  the 1/d^2 law in the CONTINUUM limit.  C compared two numbers that were
#      both mostly truncation error, which is why it flattened.  E fits
#      L2_Ham(N) = A + B N^-p at each separation and tests the 1/d^2 law on A,
#      the part refinement does not remove, with the exact single-throat
#      solution as the zero control.
#
# Usage (attached; each sub-run goes through run_single.sh so the campaign
# contract -- launcher.pid, node-local plotfile scratch -- still holds):
#   bash scripts/campaigns/wormhole_merger/phase1_initial_data.sh
# Overrides:
#   P1_GPU        CUDA device (default 0)
#   P1_RUNS_DIR   campaign root (default <repo>/runs/wormhole_merger)
#   P1_ONLY       comma list of checks to run, e.g. "A" or "B,C" (default all)
#   P1_FRESH=1    delete this script's OWN phase1_* run dirs before relaunching
#
# Every directory this script creates is named phase1_*.  It shares the
# campaign root with the evolution runs, so it only ever creates or removes
# that prefix -- P1_FRESH must never become a way to lose an evolution.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER_DIR="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
REPO_ROOT="$(cd -- "${WRAPPER_DIR}/.." && pwd)"
EXAMPLE_DIR="${REPO_ROOT}/Examples/BinaryWormholeMerger"
REF_DIR="${REPO_ROOT}/Examples/SupportedWormholeCollapse"

GPU="${P1_GPU:-0}"
RUNS_DIR="${P1_RUNS_DIR:-${REPO_ROOT}/runs/wormhole_merger}"
ONLY="${P1_ONLY:-A,B,C,D,E,F,G}"
PREFIX="phase1"
GEN_DIR="${RUNS_DIR}/${PREFIX}_params"

MERGER_EXE="${EXAMPLE_DIR}/main3d.gnu.CUDA.ex"
REF_EXE="${REF_DIR}/main3d.gnu.CUDA.ex"
FCOMPARE="$(ls -1 "${REPO_ROOT}/../amrex/Tools/Plotfile"/fcompare*.ex 2>/dev/null | head -n 1 || true)"

for exe in "${MERGER_EXE}" "${REF_EXE}"; do
  [[ -x "${exe}" ]] || { echo "[p1] missing binary: ${exe} -- build it first" >&2; exit 1; }
done

# Only ever touch our own prefix.  run_single.sh refuses to reuse an existing
# run dir, so a rerun without P1_FRESH stops instead of clobbering.
if [[ "${P1_FRESH:-0}" != "0" ]]; then
  shopt -s nullglob
  for d in "${RUNS_DIR}/${PREFIX}_"*/; do rm -rf "${d}"; done
  shopt -u nullglob
fi
mkdir -p "${GEN_DIR}"

want() { [[ ",${ONLY}," == *",$1,"* ]]; }

# ---------------------------------------------------------------------------
# Params generators.  Everything is emitted here rather than shipped as files:
# these are throwaway t = 0 probes, not configurations anyone evolves, and
# keeping them in one place makes the grid/throat parameters of each check
# readable side by side.  The three path keys are placeholders; run_single.sh
# rewrites them (and asserts each occurs exactly once).
# ---------------------------------------------------------------------------

# $1 out file, $2 L, $3 N, $4 b_A, $5 b_B, $6 zA (half-separation), $7 momentumA,
# $8 bare mass, $9 subtract_phi_asymptote
gen_merger() {
  local out=$1 L=$2 N=$3 bA=$4 bB=$5 zA=$6 pA=$7 bm=$8 sub=$9
  local c
  c="$(awk -v l="${L}" 'BEGIN{printf "%.10g", l/2}')"
  cat > "${out}" <<EOF
# Generated by phase1_initial_data.sh -- t = 0 probe, not an evolution config.
verbosity = 0
output_path    = "./output"
amr.plot_file  = "./scratch/Plt"
amr.check_file = "./scratch/Chk"
checkpoint_interval = -1
plot_interval       = 1
amr.plot_vars = chi K lapse phi Pi
data_subpath = "data"
print_progress_only_to_rank_0 = 1
particle_interpolator.verbosity = 0

wormhole_initial_lapse_type = 0
wormhole_metric_type = 2
wormhole_throat_radius_A = ${bA}
wormhole_throat_radius_B = ${bB}
wormhole_bare_mass_A = ${bm}
wormhole_bare_mass_B = ${bm}
wormhole_centerA = 0.0 0.0 ${zA}
wormhole_momentumA = ${pA}
wormhole_subtract_phi_asymptote = ${sub}
wormhole_support_strength = 1.0
phantom_mass = 0.0

L = ${L}
N = ${N}
center = ${c} ${c} ${c}
max_level = 0
regrid_interval = 32
regrid_threshold = 0.05
max_box_size = 64
min_box_size = 16
isPeriodic = 0 0 0
hi_boundary = 1 1 1
lo_boundary = 1 1 1
nonzero_asymptotic_vars = chi h11 h22 h33 lapse
nonzero_asymptotic_values = 1.0 1.0 1.0 1.0 1.0

dt_multiplier = 0.1
stop_time = 1.0e6
max_steps = 0
max_spatial_derivative_order = 4
nan_check = 1
min_chi = 1.0e-8
min_lapse = 1.0e-10
lapse_advec_coeff = 1.0
lapse_coeff = 2.0
lapse_power = 1.0
shift_advec_coeff = 1.0
shift_Gamma_coeff = 0.75
eta = 1.0
formulation = 0
kappa1 = 3.0
kappa2 = 0.
kappa3 = 1.
covariantZ4 = 0
sigma = 2.0
puncture_tracking.enabled = 0
calculate_constraint_norms = 1
binary_throat_diagnostics = 1
binary_diag_axis = 2
binary_diag_split_coord = 0.0
activate_extraction = 0
write_extraction = 0
amrex.the_arena_init_size = 1048576
EOF
}

# Reference single-throat example on the SAME grid.  It keeps its own key
# names (wormhole_throat_radius, and it still has the seeded perturbation the
# merger dropped), so it gets its own generator.
gen_reference() {
  local out=$1 L=$2 N=$3 b=$4
  local c
  c="$(awk -v l="${L}" 'BEGIN{printf "%.10g", l/2}')"
  cat > "${out}" <<EOF
# Generated by phase1_initial_data.sh -- single-throat reference at t = 0.
verbosity = 0
output_path    = "./output"
amr.plot_file  = "./scratch/Plt"
amr.check_file = "./scratch/Chk"
checkpoint_interval = -1
plot_interval       = 1
amr.plot_vars = chi K lapse phi Pi
data_subpath = "data"
print_progress_only_to_rank_0 = 1

wormhole_initial_lapse_type = 0
wormhole_throat_radius = ${b}
wormhole_centerA = 0.0 0.0 0.0
wormhole_phi_monopole_amplitude     = 0.0
wormhole_phi_perturbation_amplitude = 0.0
wormhole_phi_perturbation_width     = 0.5
wormhole_support_strength = 1.0
phantom_mass = 0.0

L = ${L}
N = ${N}
center = ${c} ${c} ${c}
max_level = 0
regrid_interval = 32
regrid_threshold = 0.05
max_box_size = 64
min_box_size = 16
isPeriodic = 0 0 0
hi_boundary = 1 1 1
lo_boundary = 1 1 1
nonzero_asymptotic_vars = chi h11 h22 h33 lapse
nonzero_asymptotic_values = 1.0 1.0 1.0 1.0 1.0

dt_multiplier = 0.1
stop_time = 1.0e6
max_steps = 0
max_spatial_derivative_order = 4
nan_check = 1
min_chi = 1.0e-8
min_lapse = 1.0e-10
lapse_advec_coeff = 1.0
lapse_coeff = 2.0
lapse_power = 1.0
shift_advec_coeff = 1.0
shift_Gamma_coeff = 0.75
eta = 1.0
formulation = 0
kappa1 = 3.0
kappa2 = 0.
kappa3 = 1.
covariantZ4 = 0
sigma = 2.0
puncture_tracking.enabled = 0
calculate_constraint_norms = 1
activate_extraction = 0
write_extraction = 0
amrex.the_arena_init_size = 1048576
EOF
}

# $1 run name, $2 params file, $3 binary
#
# WHM_CONSUME=0: the launcher's consumer sidecar deletes plotfiles as it
# reduces them, which is right for an evolution and wrong here.  Phase 1 writes
# exactly one plotfile per run, at t = 0, and checks F and G read it afterwards
# with `shells`.  Letting the sidecar collect it would delete the measurement.
launch() {
  WHM_PARAMS="$2" WHM_NAME="$1" WHM_GPU="${GPU}" WHM_RUNS_DIR="${RUNS_DIR}" \
    WHM_EXE="$3" WHM_CONSUME=0 \
    bash "${SCRIPT_DIR}/run_single.sh" > "${GEN_DIR}/$1.launch.log" 2>&1 \
    || { echo "[p1] run $1 FAILED -- see ${GEN_DIR}/$1.launch.log" >&2; return 1; }
}

# t = 0 row of constraint_norms.dat -> "L2_Ham L2_Mom"
t0_norms() {
  awk '!/^#/ && $1+0 == 0 {print $2, $3; exit}' \
    "${RUNS_DIR}/$1/data/constraint_norms.dat"
}

echo "=========================================================="
echo " Phase 1 -- initial-data validation (all runs are t = 0)"
echo " runs dir : ${RUNS_DIR}"
echo "=========================================================="

# ---------------------------------------------------------------------------
# Check A -- single-throat limit
# Resolution is irrelevant here: both codes evaluate a closed-form expression
# on the same grid, so any grid tests the formula equally.  Small and cheap.
# ---------------------------------------------------------------------------
if want A; then
  echo
  echo "== A. Single-throat limit (b_B = 0) vs SupportedWormholeCollapse =="
  gen_merger    "${GEN_DIR}/A_merger.txt" 16 64 0.5 0.0 0.0 "0.0 0.0 0.0" 0.0 0
  gen_reference "${GEN_DIR}/A_ref.txt"    16 64 0.5
  launch "${PREFIX}_A_merger_single" "${GEN_DIR}/A_merger.txt" "${MERGER_EXE}"
  launch "${PREFIX}_A_reference"     "${GEN_DIR}/A_ref.txt"    "${REF_EXE}"
  echo "-- fcompare (chi, lapse, K, phi, Pi) --"
  if [[ -n "${FCOMPARE}" ]]; then
    "${FCOMPARE}" \
      "${GRTECLYN_SCRATCH:-/tmp/grteclyn_scratch}/${PREFIX}_A_merger_single/BinaryWormholePlt00000" \
      "${GRTECLYN_SCRATCH:-/tmp/grteclyn_scratch}/${PREFIX}_A_reference/BinaryWormholePlt00000" \
      || true
  else
    echo "   fcompare not built -- build amrex/Tools/Plotfile"
  fi
fi

# ---------------------------------------------------------------------------
# Check B -- momentum constraint at t = 0
# With zero momenta A_ij is identically zero, so every derivative of it is
# exactly zero and L2_Mom must be 0 to the last bit.  With Bowen-York momenta
# on, the constraint is analytically zero but the DISCRETE divergence is not:
# it carries the 4th-order truncation error of the stencil.  The gate is
# therefore convergence at ~4th order, not a bit-level zero -- a non-convergent
# or O(1) value is the bug this check exists to catch.
# ---------------------------------------------------------------------------
if want B; then
  echo
  echo "== B. Momentum constraint at t = 0 =="
  gen_merger "${GEN_DIR}/B_nop.txt" 16 64 0.5 0.5 2.0 "0.0 0.0 0.0" 0.25 1
  launch "${PREFIX}_B_no_momenta" "${GEN_DIR}/B_nop.txt" "${MERGER_EXE}"
  echo "   momenta off : L2_Ham L2_Mom = $(t0_norms "${PREFIX}_B_no_momenta")"
  for N in 64 96 128; do
    gen_merger "${GEN_DIR}/B_p_N${N}.txt" 16 "${N}" 0.5 0.5 2.0 "0.0 0.088 0.0" 0.25 1
    launch "${PREFIX}_B_momenta_N${N}" "${GEN_DIR}/B_p_N${N}.txt" "${MERGER_EXE}"
    echo "   momenta on  N=${N} (dx=$(awk -v n=${N} 'BEGIN{printf "%.5g",16.0/n}')) : L2_Ham L2_Mom = $(t0_norms "${PREFIX}_B_momenta_N${N}")"
  done
fi

# ---------------------------------------------------------------------------
# Check C -- Hamiltonian defect scales as 1/d^2
# b = 1 with dx = 1/12 keeps ~6 cells across the isotropic throat radius b/2,
# so the superposition defect is not buried in discretisation error.  The
# single-throat run on the identical grid is the floor to compare against.
# ---------------------------------------------------------------------------
if want C; then
  echo
  echo "== C. Hamiltonian defect vs separation (fixed grid L=32 N=384) =="
  gen_merger "${GEN_DIR}/C_floor.txt" 32 384 1.0 0.0 2.0 "0.0 0.0 0.0" 0.0 1
  launch "${PREFIX}_C_floor_single" "${GEN_DIR}/C_floor.txt" "${MERGER_EXE}"
  echo "   single throat (floor)   : L2_Ham L2_Mom = $(t0_norms "${PREFIX}_C_floor_single")"
  for d in 4 8 16; do
    zA="$(awk -v d="${d}" 'BEGIN{printf "%.10g", d/2}')"
    gen_merger "${GEN_DIR}/C_d${d}.txt" 32 384 1.0 1.0 "${zA}" "0.0 0.0 0.0" 0.0 1
    launch "${PREFIX}_C_d${d}" "${GEN_DIR}/C_d${d}.txt" "${MERGER_EXE}"
    echo "   d = ${d} (d/b = ${d})          : L2_Ham L2_Mom = $(t0_norms "${PREFIX}_C_d${d}")"
  done
fi

# ---------------------------------------------------------------------------
# Check D -- resolution study, the control B and C both need
#
# B and C as first run were both contaminated, in ways only a refinement ladder
# can separate:
#
#   * B carried a BARE MASS, i.e. a puncture.  chi -> 0 there and the
#     Hamiltonian constraint is formally singular, so its whole-domain L2 norm
#     has no continuum limit -- and indeed L2_Ham came out NON-MONOTONIC in N.
#     The throat was also only ~1-2 cells across (b = 0.5, dx = 0.25..0.125),
#     nowhere near the asymptotic regime, so the order it reported measured the
#     under-resolution, not the stencil.
#   * C flattened between d = 8 and d = 16, which is what a measurement sitting
#     on its own error floor looks like.
#
# D fixes both: b = 1 resolved over 3 -> 6 cells of the isotropic throat radius,
# NO bare mass so there is no puncture anywhere in the domain, and the SAME
# ladder run for the single throat (floor), the binary at d = 8, and the
# momentum constraint.  If the floor converges at the stencil order while the
# binary's excess over it does not, the excess is the superposition defect and
# C's gate is meaningful; if floor and binary fall together, C is floor-limited
# and the gate needs a norm that excludes the throats.
# ---------------------------------------------------------------------------
if want D; then
  echo
  echo "== D. Resolution ladder at L=32, b=1, NO bare mass (no puncture) =="
  for N in 192 288 384; do
    dx="$(awk -v n="${N}" 'BEGIN{printf "%.5g", 32.0/n}')"
    gen_merger "${GEN_DIR}/D_floor_N${N}.txt" 32 "${N}" 1.0 0.0 4.0 "0.0 0.0 0.0" 0.0 1
    launch "${PREFIX}_D_floor_N${N}" "${GEN_DIR}/D_floor_N${N}.txt" "${MERGER_EXE}"
    echo "   floor  N=${N} (dx=${dx}) : $(t0_norms "${PREFIX}_D_floor_N${N}")"

    gen_merger "${GEN_DIR}/D_d8_N${N}.txt" 32 "${N}" 1.0 1.0 4.0 "0.0 0.0 0.0" 0.0 1
    launch "${PREFIX}_D_d8_N${N}" "${GEN_DIR}/D_d8_N${N}.txt" "${MERGER_EXE}"
    echo "   d=8    N=${N} (dx=${dx}) : $(t0_norms "${PREFIX}_D_d8_N${N}")"

    gen_merger "${GEN_DIR}/D_mom_N${N}.txt" 32 "${N}" 1.0 1.0 4.0 "0.0 0.088 0.0" 0.0 1
    launch "${PREFIX}_D_mom_N${N}" "${GEN_DIR}/D_mom_N${N}.txt" "${MERGER_EXE}"
    echo "   mom    N=${N} (dx=${dx}) : $(t0_norms "${PREFIX}_D_mom_N${N}")"
  done
fi

# ---------------------------------------------------------------------------
# Check E -- the 1/d^2 law, measured in the CONTINUUM limit
#
# D settled why C flattened.  The single throat is an exact solution, and its
# L2_Ham falls at ~3.3-3.5 order, i.e. it is pure discretisation error on its
# way to zero.  The binary at the SAME grid falls at ~3.0-3.3.  So at every
# resolution C could afford, most of what C measured was truncation error, not
# superposition defect, and subtracting "the floor" from it subtracts two
# numbers of the same size -- which is exactly the flat, meaningless ratio C
# reported.
#
# The fix is not a bigger grid, it is a different estimator.  Fit
#
#     L2_Ham(N) = A + B N^-p
#
# to a three-point ladder at each separation.  A is the part that does NOT go
# away under refinement: the continuum superposition defect.  B N^-p is the
# truncation error, which does.  The single-throat ladder is the control -- it
# is an exact solution, so its A must come out zero, and however far from zero
# it lands is the error bar on every other A.
#
# The gate then reads: A(d) falls like 1/d^2.
# ---------------------------------------------------------------------------
if want E; then
  echo
  echo "== E. Continuum superposition defect vs separation (3-point ladder per d) =="
  for N in 192 288 384; do
    for d in 4 16; do
      zA="$(awk -v x="${d}" 'BEGIN{printf "%.10g", x/2}')"
      gen_merger "${GEN_DIR}/E_d${d}_N${N}.txt" 32 "${N}" 1.0 1.0 "${zA}" "0.0 0.0 0.0" 0.0 1
      launch "${PREFIX}_E_d${d}_N${N}" "${GEN_DIR}/E_d${d}_N${N}.txt" "${MERGER_EXE}"
      echo "   d=${d} N=${N} : $(t0_norms "${PREFIX}_E_d${d}_N${N}")"
    done
  done
  # d = 8 and the single-throat control are D's ladder -- same generator call,
  # same grid, so rerunning them would only burn GPU time on identical numbers.
  echo
  python3 - "${RUNS_DIR}" "${PREFIX}" <<'PYEOF'
import math, os, sys

runs_dir, prefix = sys.argv[1], sys.argv[2]

def t0(name):
    path = os.path.join(runs_dir, name, "data", "constraint_norms.dat")
    with open(path) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            cols = line.split()
            if float(cols[0]) == 0.0:
                return float(cols[1])
    raise SystemExit(f"no t = 0 row in {path}")

NS = (192, 288, 384)

def fit(f):
    """Solve f(N) = A + B N^-p for the three-point ladder f."""
    f1, f2, f3 = f
    d12, d23 = f1 - f2, f2 - f3
    if d12 <= 0 or d23 <= 0:
        return None, None            # not monotonically converging: no fit
    h = [NS[-1] / n for n in NS]     # grid spacing in units of the finest
    target = d12 / d23
    lo, hi = 0.2, 12.0
    for _ in range(200):             # bisect on p; RHS is monotone in p
        p = 0.5 * (lo + hi)
        rhs = (h[0]**p - h[1]**p) / (h[1]**p - h[2]**p)
        if rhs < target:
            lo = p
        else:
            hi = p
    p = 0.5 * (lo + hi)
    B_hfine = d23 / (h[1]**p - h[2]**p)   # = B * h_finest^p
    return f3 - B_hfine, p

ladders = {
    "single throat (control)": [f"{prefix}_D_floor_N{n}" for n in NS],
    "d = 4":                   [f"{prefix}_E_d4_N{n}"    for n in NS],
    "d = 8":                   [f"{prefix}_D_d8_N{n}"    for n in NS],
    "d = 16":                  [f"{prefix}_E_d16_N{n}"   for n in NS],
}

print("   L2_Ham(t=0) ladder and its continuum limit A")
print(f"   {'case':24s} {'N=192':>11s} {'N=288':>11s} {'N=384':>11s} {'order p':>8s} {'A':>11s}")
A = {}
for label, names in ladders.items():
    f = [t0(n) for n in names]
    a, p = fit(f)
    A[label] = a
    ptxt = f"{p:8.2f}" if p is not None else f"{'--':>8s}"
    atxt = f"{a:11.3e}" if a is not None else f"{'--':>11s}"
    print(f"   {label:24s} {f[0]:11.4e} {f[1]:11.4e} {f[2]:11.4e} {ptxt} {atxt}")

err = abs(A["single throat (control)"] or 0.0)
print(f"\n   control A = {A['single throat (control)']:.3e}  ->  error bar on every A is ~{err:.1e}")
print("   (the single throat is an exact solution, so its A is zero by construction)")
print("\n   1/d^2 gate:  A(d) should fall by 4x each time d doubles")
for a_lab, b_lab in (("d = 4", "d = 8"), ("d = 8", "d = 16")):
    a, b = A[a_lab], A[b_lab]
    if a is None or b is None:
        print(f"   {a_lab} -> {b_lab}: no fit")
        continue
    sig = "  [BELOW THE ERROR BAR - not a measurement]" if min(abs(a), abs(b)) < 2 * err else ""
    print(f"   {a_lab} -> {b_lab}: ratio {a / b:6.2f}   (predicted 4){sig}")
PYEOF
fi

# ---------------------------------------------------------------------------
# Shell profiles.  The plotfile consumer already knows how to reduce a plotfile
# onto spherical shells, so nothing here parses a plotfile itself.  Runs after
# the fact on the plotfile the run left on scratch -- Phase 1 sets max_steps = 0,
# so there is exactly one, at t = 0.
#
# $1 run name, $2 radii (space separated), $3 fields (space separated),
# $4 domain centre (a single coordinate; the grid is a cube centred on L/2)
# ---------------------------------------------------------------------------
shells() {
  local name=$1 radii=$2 fields=$3 c=$4
  local scratch="${GRTECLYN_SCRATCH:-/tmp/grteclyn_scratch}/${name}"
  local out="${RUNS_DIR}/${name}/small_data"
  mkdir -p "${out}"
  # shellcheck disable=SC2086
  "${WRAPPER_DIR}/.venv/bin/python" -m \
    grteclyn_wrapper.visualisation.process_wave.consume_plotfiles \
    --data "${scratch}" --out "${out}" --no-psi4 \
    --shell-fields ${fields} --radii ${radii} --n-points 32 \
    --center "${c}" "${c}" "${c}" --stable-seconds 0 >/dev/null 2>&1
  echo "${out}/shell_profiles.dat"
}

# ---------------------------------------------------------------------------
# Check F -- phi really does tend to zero at the outer boundary
#
# The gate exists because the Sommerfeld boundary condition assumes the field
# it is applied to decays to zero there.  An Ellis-Bronnikov scalar does not:
# it tends to a CONSTANT, and if that constant is left in place the boundary
# condition is wrong from the first step.  wormhole_subtract_phi_asymptote
# removes it.
#
# The gate cannot be "phi < 1e-3 at the boundary", though, and the plan's
# wording asks for exactly that.  After the constant is removed what is left is
# the physical tail, and for this field that tail falls like 1/r -- so pushing
# it below 1e-3 needs a domain hundreds of throat radii wide, which no run in
# this campaign will ever have.  Fitting the constant out of a single run does
# not work either: over the radii a finite box offers, a constant, a 1/r and a
# 1/r^2 term are not separable, and the fitted constant moves around with the
# radius range and even changes sign.
#
# So F measures the constant directly instead, by DIFFERENCING two runs that
# are identical but for the subtraction.  That difference is the subtracted
# constant, with nothing else in it, and no fit involved.
# ---------------------------------------------------------------------------
if want F; then
  echo
  echo "== F. phi at the outer boundary (subtraction on vs off) =="
  RADII_F="6 8 10 12 14 15"
  for sub in 0 1; do
    gen_merger "${GEN_DIR}/F_sub${sub}.txt" 32 192 1.0 0.0 0.0 "0.0 0.0 0.0" 0.0 "${sub}"
    launch "${PREFIX}_F_sub${sub}" "${GEN_DIR}/F_sub${sub}.txt" "${MERGER_EXE}"
    shells "${PREFIX}_F_sub${sub}" "${RADII_F}" "chi phi" 16 >/dev/null
  done
  python3 - "${RUNS_DIR}" "${PREFIX}" ${RADII_F} <<'F_PY'
import sys
runs_dir, prefix = sys.argv[1], sys.argv[2]
R = [int(x) for x in sys.argv[3:]]

def prof(name):
    path = f"{runs_dir}/{name}/small_data/shell_profiles.dat"
    lines = [l for l in open(path) if l.strip()]
    hdr = lines[0].lstrip("#").split()
    return dict(zip(hdr, lines[1].split()))

off, on = prof(f"{prefix}_F_sub0"), prof(f"{prefix}_F_sub1")
print(f"   {'r':>4} {'phi (sub OFF)':>15} {'phi (sub ON)':>15} {'difference':>13} {'phi_on * r':>11}")
diffs = []
for r in R:
    a = float(off[f"phi_mean_R{r}"]); b = float(on[f"phi_mean_R{r}"])
    diffs.append(a - b)
    print(f"   {r:>4} {a:15.6e} {b:15.6e} {a-b:13.6f} {b*r:11.5f}")

spread = max(diffs) - min(diffs)
mean = sum(diffs) / len(diffs)
print(f"\n   subtracted constant = {mean:.6f}  (spread across radii {spread:.2e})")
print("   A constant is constant: the spread is the check that this is really")
print("   an offset and not something with structure that happens to be large.")

bound_off = float(off[f"phi_mean_R{R[-1]}"]); bound_on = float(on[f"phi_mean_R{R[-1]}"])
print(f"\n   at the outermost shell r = {R[-1]}:")
print(f"     subtraction OFF : phi = {bound_off:+.4f}   <- what Sommerfeld would see")
print(f"     subtraction ON  : phi = {bound_on:+.4f}   ({abs(bound_off/bound_on):.0f}x smaller)")
prods = [float(on[f"phi_mean_R{r}"]) * r for r in R]
print(f"\n   phi_on * r over r = {R[0]}..{R[-1]}: {prods[0]:.4f} -> {prods[-1]:.4f}")
print("   Near-constant means the residual is the physical 1/r tail with no")
print("   constant left in it -- a leftover offset would make this grow with r.")
F_PY
fi

# ---------------------------------------------------------------------------
# Check G -- the bare-mass tail weighs what the orbit calculation assumes
#
# Phase 3 picks its separation and stop_time from a Newtonian free-fall time
# built out of m_A + m_B.  That is only meaningful if the spacetime really
# carries that much mass, so read the ADM mass off the far field and compare.
#
# psi -> 1 + M/(2r) at large r.  The fit deliberately has NO constant term:
# psi tends to exactly 1 by construction, and leaving a constant free is what
# made the phi fit in F degenerate.  The 1/r^2 term is the throat's own
# structure, which has to be there or it contaminates the 1/r coefficient.
# ---------------------------------------------------------------------------
if want G; then
  echo
  echo "== G. Bare-mass tail: does psi - 1 recover m_A + m_B? =="
  # Two domains with the SAME physics (throats at z = +-4, b = 1, m = 0.25
  # each).  L = 32 leaves only r = 8..15 of far field -- barely a factor of two
  # in r, with the throats' own 1/r^2 structure and the binary's quadrupole
  # still large there, so the fitted mass depends on how many terms are kept.
  # L = 64 pushes the outermost shell to r = 30, where those corrections are
  # down by roughly (8/30)^2.  If M converges on m_A + m_B as the far field
  # opens up, the tail is right and the L = 32 spread was series truncation.
  gen_merger "${GEN_DIR}/G_mass_L32.txt" 32 192 1.0 1.0 4.0 "0.0 0.0 0.0" 0.25 1
  launch "${PREFIX}_G_mass_L32" "${GEN_DIR}/G_mass_L32.txt" "${MERGER_EXE}"
  shells "${PREFIX}_G_mass_L32" "8 10 12 14 15" "chi" 16 >/dev/null

  gen_merger "${GEN_DIR}/G_mass_L64.txt" 64 384 1.0 1.0 4.0 "0.0 0.0 0.0" 0.25 1
  launch "${PREFIX}_G_mass_L64" "${GEN_DIR}/G_mass_L64.txt" "${MERGER_EXE}"
  shells "${PREFIX}_G_mass_L64" "12 16 20 24 28 30" "chi" 32 >/dev/null

  python3 - "${RUNS_DIR}" "${PREFIX}" <<'G_PY'
import sys
runs_dir, prefix = sys.argv[1], sys.argv[2]
M_EXPECTED = 0.5   # m_A + m_B, both 0.25

LADDER = [("L=32", f"{prefix}_G_mass_L32", [8, 10, 12, 14, 15]),
          ("L=64", f"{prefix}_G_mass_L64", [12, 16, 20, 24, 28, 30])]

def lstsq(basis, y):
    n, m = len(y), len(basis)
    A = [[sum(basis[i][k] * basis[j][k] for k in range(n)) for j in range(m)] for i in range(m)]
    b = [sum(basis[i][k] * y[k] for k in range(n)) for i in range(m)]
    for i in range(m):
        p = max(range(i, m), key=lambda r_: abs(A[r_][i]))
        A[i], A[p] = A[p], A[i]; b[i], b[p] = b[p], b[i]
        for r_ in range(i + 1, m):
            f = A[r_][i] / A[i][i]
            for c in range(i, m):
                A[r_][c] -= f * A[i][c]
            b[r_] -= f * b[i]
    x = [0.0] * m
    for i in reversed(range(m)):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, m))) / A[i][i]
    return x

print(f"   expected m_A + m_B = {M_EXPECTED:.5f}\n")
print(f"   {'domain':>7} {'r range':>10} {'M (1 term)':>12} {'M (2 terms)':>12} "
      f"{'M (3 terms)':>12} {'dev':>7} {'rms resid':>10}")
for label, name, R in LADDER:
    path = f"{runs_dir}/{name}/small_data/shell_profiles.dat"
    lines = [l for l in open(path) if l.strip()]
    d = dict(zip(lines[0].lstrip("#").split(), lines[1].split()))
    # chi = psi^-4  =>  psi = chi^(-1/4)
    psi = [float(d[f"chi_mean_R{r}"]) ** -0.25 for r in R]
    y = [p - 1.0 for p in psi]
    powers = [[1.0 / r ** k for r in R] for k in (1, 2, 3)]
    Ms, rms = [], None
    for nterm in (1, 2, 3):
        basis = powers[:nterm]
        c = lstsq(basis, y)
        Ms.append(2 * c[0])
        pred = [sum(b[k] * ci for b, ci in zip(basis, c)) for k in range(len(R))]
        rms = (sum((a - b) ** 2 for a, b in zip(y, pred)) / len(y)) ** 0.5
    dev = 100 * abs(Ms[-1] - M_EXPECTED) / M_EXPECTED
    print(f"   {label:>7} {f'{R[0]}-{R[-1]}':>10} {Ms[0]:12.5f} {Ms[1]:12.5f} "
          f"{Ms[2]:12.5f} {dev:6.2f}% {rms:10.2e}")

print("\n   Read the 3-term column, and read it across the two domains rather")
print("   than as a single number: psi-1 is an asymptotic series, so each")
print("   truncation lands on alternating sides of the true mass, and what")
print("   shows the tail is right is the deviation shrinking as the far field")
print("   opens up.")
G_PY
fi

echo
echo "=========================================================="
echo " raw t = 0 constraint norms"
printf ' %-24s %-22s %s\n' run L2_Ham L2_Mom
for d in "${RUNS_DIR}"/*/; do
  n="$(basename "${d}")"
  [[ "${n}" != "${PREFIX}_"* || "${n}" == "${PREFIX}_params" ]] && continue
  [[ -f "${d}/data/constraint_norms.dat" ]] || continue
  # shellcheck disable=SC2046
  printf ' %-24s %-22s %s\n' "${n}" $(t0_norms "${n}")
done
echo "=========================================================="
